### ISSUE TITLE
Remove meta keywords

### ISSUE THREAD

**Issue by matfantinel** [matfantinel/fantinel.dev#41]
~Right now the blog post's tags are being used as keywords for SEO, which is not optimal since that's not their intended use. Adding keywords to a post's Frontmatter will allow cleaning up the tags AND improve SEO.~

Meta keywords are no longer relevant (and haven't been for a while). I can safely delete those from the code with no impact to SEO.

**Comment by matfantinel** [comment]
Keywords are now working, but I need to go back and add them to the older posts.

**Comment by Bishwas-py** [comment]
@matfantinel Is this done? Can I work on it?

**Comment by matfantinel** [comment]
@Bishwas-py I had started doing it but stopped after seeing that apparently the meta keywords tag [is ignored on all major search engines](https://datadrivenlabs.io/blog/meta-keyword-tag-google-2018/), and has been for some time. So not sure if there's any use case for having them, to be honest
