### ISSUE TITLE
Do you want a cat running through your website?

### ISSUE THREAD

**Issue by ABSanthosh** [matfantinel/fantinel.dev#62]
You have a pretty neat portfolio! I thought you might like [neko-ts](https://github.com/ABSanthosh/neko-ts). You can check how it works [here in my portfolio](https://abs.moe/) (Scroll to the bottom and enable `Neko` checkbox to see it working). Its a remake of [xneko](https://eliotakira.com/neko/) from MS-DOS.

Happy coding!

**Comment by matfantinel** [comment]
Hey there! Thanks for the kind words. It's not really my style but nice work on the project!
