### ISSUE TITLE
Happy 5th Anniversary

### ISSUE THREAD

**Issue by MaxDaten** [matfantinel/fantinel.dev#72]
Hi, 

first of all, thank you providing your site as a template so I can use it [myself an tinker around with it](https://www.maxdaten.io/). Everyone gives compliments to my my new site even if they are a little less impressed when I tell the I stole it from you :) 

While reading you recent blog post just noticed a broken link:

https://github.com/matfantinel/fantinel.dev/blame/6e0177fdacb5bb4e9d020916b5b939e1f6d0e3a1/cms/articles/2024-03-08-5-year-blog-anniversary.md#L59

Kudos and thank you again!

Jan

**Comment by matfantinel** [comment]
@MaxDaten Thank you for the kind words and for pointing out the broken link! That has been fixed ;)
